id = "lorem-snippets"
name = "Lorem Ipsum Snippets"
version = "0.1.0"
schema-version = 1
authors = ["Umut Ertuğrul Daşgın <ertugruldasgin@gmail.com>"]
description = "Quick Lorem Ipsum snippets for any file. Just type 'lorem' and select the desired snippet from the suggestions."
repository = "https://github.com/ertugruldasgin/lorem-snippets.git"
snippets = ["./snippets/snippets.json"]